name: WSD4HA
version: "0.61"
# _.xx._  reflects the implemented packet in the wireshark reference, max = x.46
slug: wsd_scanner
description: "Minimal WSD-Server for Samsung C480W [and probably other Scanners]"
url: https://github.com/rossi75/WSD4HA
webui: http://[HOST]:[PORT:8110]
arch:
  - amd64
  - aarch64
#startup: "application"
startup: services
#boot: "auto"
init: false
ports:
  8110/tcp: 8110
  5357/tcp: 5357
host_network: true
map:
#  - "{{ options.scan_folder }}:rw"
  - config:rw
options:
  offline_timeout: 300
  displayname: "Scan to Home Assistant"
  scan_folder: "/share/scans"
  max_files: 50
#  log_level: "INFO"
  log_level: []
schema:
  offline_timeout: int(120,3600)
  displayname: str
  scan_folder: str
  max_files: int
  log_level: list(ERROR|WARNING|INFO|DEBUG)
