name: WSD Scanner
version: "0.1.02"
slug: wsd_scanner
description: "Minimaler WSD-Server [für Samsung C480W und ggf andere Scanner]"
arch:
  - amd64
  - aarch64
#startup: "application"
startup: services
#boot: "auto"
init: false
ports:
#  - 8080:8080
  8080/tcp: 8080
  3702/udp: 3702
  1900/udp: 1900
schema:
  scan_folder: str
  max_files: int
  http_port: int
  scanner_offline_timeout: int
options:
  scan_folder: "/share/scans"
  max_files: 5
  http_port: 8080
  scanner_offline_timeout: 300
map:
#  - "{{ options.scan_folder }}:rw"
  - config:rw
environment:
  WSD_SCAN_FOLDER: "{{ options.scan_folder }}"
  WSD_MAX_FILES: "{{ options.max_files }}"
  WSD_HTTP_PORT: "{{ options.http_port }}"
  WSD_OFFLINE_TIMEOUT: "{{ options.scanner_offline_timeout }}"
