name: WSD Scanner
version: "0.002"
slug: wsd_scanner
description: "Minimaler WSD-Server [für Samsung C480W und ggf andere Scanner]"
url: https://github.com/rossi75/WSD4HA
webui: http://[HOST]:[PORT:8110]
arch:
  - amd64
  - aarch64
#startup: "application"
startup: services
#boot: "auto"
init: false
ports:
  8110/tcp: 8110
  3702/udp: 3702
#  1900/udp: 1900
host_network: true
schema:
  scan_folder: str
  max_files: int
  scanner_offline_timeout: int
options:
  scan_folder: "/share/scans"
  max_files: 50
  scanner_offline_timeout: 300
map:
#  - "{{ options.scan_folder }}:rw"
  - config:rw
environment:
  WSD_SCAN_FOLDER: "{{ options.scan_folder }}"
  WSD_MAX_FILES: "{{ options.max_files }}"
  WSD_OFFLINE_TIMEOUT: "{{ options.scanner_offline_timeout }}"
