name: WSD Scanner
version: "0.1"
slug: wsd_scanner
description: "Minimaler WSD-Server für Samsung C480W"
arch:
  - amd64
  - aarch64
startup: "application"
boot: "auto"
ports:
  - 8080:8080
options:
  scan_folder: "/share/scans"
  max_files: 5
  http_port: 8080
  scanner_offline_timeout: 300
schema:
  scan_folder: str
  max_files: int
  http_port: int
  scanner_offline_timeout: int
map:
  - "{{ options.scan_folder }}:rw"
environment:
  WSD_SCAN_FOLDER: "{{ options.scan_folder }}"
  WSD_MAX_FILES: "{{ options.max_files }}"
  WSD_HTTP_PORT: "{{ options.http_port }}"
  WSD_OFFLINE_TIMEOUT: "{{ options.scanner_offline_timeout }}"
