name: WSD4HA
version: "0.00.4_"
slug: wsd_scanner
#description: "Minimaler WSD-Server für den Scanneranteil am Samsung C480W [und ggf andere Scanner]"
description: "Minimal WSD-Server for Samsung C480W [and probably other Scanners]"
url: https://github.com/rossi75/WSD4HA
webui: http://[HOST]:[PORT:8110]
arch:
  - amd64
  - aarch64
#startup: "application"
startup: services
#boot: "auto"
init: false
ports:
  8110/tcp: 8110
host_network: true
map:
#  - "{{ options.scan_folder }}:rw"
  - config:rw
options:
  offline_timeout: 300
  scan_folder: "/share/scans"
  max_files: 50
  log_level: "INFO"
schema:
  offline_timeout: int(120,3600)
  scan_folder: str
  max_files: int
  log_level: list(INFO|DEBUG|WARNING|ERROR)
environment:
  OFFLINE_TIMEOUT: "{{ options.offline_timeout }}"
  SCAN_FOLDER: "{{ options.scan_folder }}"
  MAX_FILES: "{{ options.max_files }}"
  LOG_LEVEL: "{{ options.log_level }}"
